#!/usr/bin/env bash
#
# Updates rclone to the latest version using the modified install script which uses the GitHub mirror.
# If the update is not necessary or fails after a number of attempts, the script exits cleanly to avoid
# cascading service failures when rclone is already installed.

# Exponential backoff parameters
BASE=2
ATTEMPT=0
MAX_ATTEMPTS=5

# Cleanup hook
cleanup() {
  rm -f "$TMPFILE"
}
trap cleanup EXIT

# Function to check if rclone is installed and return version
function check_rclone_installed {
  if ! command -v rclone &> /dev/null; then
    return 1
  else
    rclone --version
    return 0
  fi
}

# Main update loop with exponential backoff
while (( ATTEMPT < MAX_ATTEMPTS )); do
  # Create a temp file to download the install script
  TMPFILE=$(mktemp)

  # Download the install.sh script into the temp file
  curl -s https://rclone.org/install.sh -o "$TMPFILE"

  # Modify the install.sh script to replace the hardcoded download URL
  sed -i "s~curl -OfsS~curl -OfsSL~g" "$TMPFILE"
  sed -i "s~download_link=\"https://downloads.rclone.org/~download_link=\"https://github.com/rclone/rclone/releases/download/v\${current_version#rclone v}/~g" "$TMPFILE"
  sed -i "s~rclone-current-\${OS}-\${OS_type}\.zip~rclone-v\${current_version#rclone v}-\${OS}-\${OS_type}.zip~g" "$TMPFILE"
  
  # Install or update rclone using the modified script
  sudo bash "$TMPFILE"
  RC=$?  # Capture the exit code of the install/update command

  # Exit code 3 indicates no update is needed
  if [[ $RC -eq 3 ]]; then
    echo "No update is needed for rclone."
    exit 0
  # Exit code 0 indicates the update was successful
  elif [[ $RC -eq 0 ]]; then
    echo "rclone successfully updated."
    exit 0
  else
    # Exponentially back off and retry update
    (( ATTEMPT++ ))
    echo "Update failed. Attempt $ATTEMPT/$MAX_ATTEMPTS failed."
    DELAY=$(( BASE**ATTEMPT ))
    echo "Retrying after $DELAY seconds..."
    sleep "$DELAY"
  fi
done

# If there is a working version of rclone, after all attempts fail, exit cleanly to avoid cascading failures
if check_rclone_installed; then
  echo "rclone update failed, but a working version is installed."
  exit 0
else
  echo "rclone update failed and rclone is not installed."
  exit 1
fi
